### ISSUE TITLE
Splitting item stacks in bag

### ISSUE THREAD

**Issue by Kamie1** [doorknob6/pfUI-turtle#6]
Shift - left mouse button / Shift - right mouse button won't split stacks of items in the bag, so makes trading really hard.

Without the UI installed splitting stacks works fine, but when you install it again, it just stops splitting stacks.

No option to enable inside pfui settings if I missed it.

**Comment by doorknob6** [comment]
Hi, thanks for opening this issue.
As this extension addon does not make any changes to the [base addon](https://github.com/shagu/pfUI)'s bag functionality, I recommend opening an issue [there](https://github.com/shagu/pfUI/issues).
